//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billbox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentUserLevel
    {
        public AgentUserLevel()
        {
            this.AgentUsers = new HashSet<AgentUser>();
            this.AgentUserRights = new HashSet<AgentUserRight>();
        }
    
        public int LevelId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AgentUser> AgentUsers { get; set; }
        public virtual ICollection<AgentUserRight> AgentUserRights { get; set; }
    }
}
