//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billbox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parish
    {
        public Parish()
        {
            this.Agents = new HashSet<Agent>();
            this.Subscribers = new HashSet<Subscriber>();
            this.Users = new HashSet<User>();
        }
    
        public int ParishId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Agent> Agents { get; set; }
        public virtual ICollection<Subscriber> Subscribers { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
