//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billbox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.PaymentCaptureFields = new HashSet<PaymentCaptureField>();
            this.PaymentInfoes = new HashSet<PaymentInfo>();
            this.PaymentPaymentTypeCaptureFields = new HashSet<PaymentPaymentTypeCaptureField>();
        }
    
        public int PaymentId { get; set; }
        public int SubscriberId { get; set; }
        public int InvoiceNumber { get; set; }
        public int AgentId { get; set; }
        public int AgentBranchId { get; set; }
        public int AgentUserId { get; set; }
        public System.DateTime Date { get; set; }
        public byte[] Time { get; set; }
        public int Status { get; set; }
    
        public virtual Subscriber Subscriber { get; set; }
        public virtual ICollection<PaymentCaptureField> PaymentCaptureFields { get; set; }
        public virtual ICollection<PaymentInfo> PaymentInfoes { get; set; }
        public virtual ICollection<PaymentPaymentTypeCaptureField> PaymentPaymentTypeCaptureFields { get; set; }
    }
}
