//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillBox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.PaymentPaymentMethodCaptureFields = new HashSet<PaymentPaymentMethodCaptureField>();
        }
    
        public int PaymentId { get; set; }
        public int PaymentMethodId { get; set; }
        public int BillId { get; set; }
        public double Amount { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual ICollection<PaymentPaymentMethodCaptureField> PaymentPaymentMethodCaptureFields { get; set; }
    }
}
