//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billbox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentPaymentTypeCaptureField
    {
        public int PaymentId { get; set; }
        public int PaymentTypeCaptureFieldId { get; set; }
        public string Value { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual PaymentTypeCaptureField PaymentTypeCaptureField { get; set; }
    }
}
