//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillBox.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agent> Agents { get; set; }
        public DbSet<AgentBranch> AgentBranches { get; set; }
        public DbSet<CaptureField> CaptureFields { get; set; }
        public DbSet<Parish> Parishes { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<PaymentCaptureField> PaymentCaptureFields { get; set; }
        public DbSet<PaymentInfo> PaymentInfoes { get; set; }
        public DbSet<PaymentPaymentTypeCaptureField> PaymentPaymentTypeCaptureFields { get; set; }
        public DbSet<PaymentType> PaymentTypes { get; set; }
        public DbSet<PaymentTypeCaptureField> PaymentTypeCaptureFields { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<Subscriber> Subscribers { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserLevel> UserLevels { get; set; }
        public DbSet<UserRight> UserRights { get; set; }
    }
}
