//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillBox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillCaptureField
    {
        public int BillId { get; set; }
        public int CaptureFieldId { get; set; }
        public string Value { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual CaptureField CaptureField { get; set; }
    }
}
