//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillBox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaptureField
    {
        public CaptureField()
        {
            this.BillCaptureFields = new HashSet<BillCaptureField>();
        }
    
        public int CaptureFieldId { get; set; }
        public int SubscriberId { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<int> OrderNum { get; set; }
    
        public virtual ICollection<BillCaptureField> BillCaptureFields { get; set; }
        public virtual Subscriber Subscriber { get; set; }
    }
}
