//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billbox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginSession
    {
        public System.Guid SessionId { get; set; }
        public string UserType { get; set; }
        public int UserUniqueIdentifier { get; set; }
        public System.DateTime LastActiveAt { get; set; }
        public System.DateTime ExpireAt { get; set; }
    }
}
