//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billbox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentType
    {
        public PaymentType()
        {
            this.PaymentInfoes = new HashSet<PaymentInfo>();
            this.PaymentTypeCaptureFields = new HashSet<PaymentTypeCaptureField>();
        }
    
        public int PaymentTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PaymentInfo> PaymentInfoes { get; set; }
        public virtual ICollection<PaymentTypeCaptureField> PaymentTypeCaptureFields { get; set; }
    }
}
