//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillBox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        public Subscriber()
        {
            this.Bills = new HashSet<Bill>();
            this.CaptureFields = new HashSet<CaptureField>();
        }
    
        public int SubscriberId { get; set; }
        public string Name { get; set; }
        public string OperatingName { get; set; }
        public string AddressStreet { get; set; }
        public string AddressCity { get; set; }
        public int ParishId { get; set; }
        public string ContactNumber { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Website { get; set; }
    
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<CaptureField> CaptureFields { get; set; }
        public virtual Parish Parish { get; set; }
    }
}
