//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillBox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLevel
    {
        public UserLevel()
        {
            this.Users = new HashSet<User>();
            this.UserRights = new HashSet<UserRight>();
        }
    
        public int LevelId { get; set; }
        public string LevelName { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<UserRight> UserRights { get; set; }
    }
}
